### ISSUE TITLE
MAX_SEARCH_DISTANCE

### ISSUE THREAD

**Issue by Feifei413666** [jagodki/Offline-MapMatching#50]
I encountered this problem during the process of using this plugin. If I set MAX_SEARCH_DISTANCE too small, the code won't run, but if I set it too large, the following problem will occur.

Traceback (most recent call last):
File "C:\Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Offline-MapMatching\mm_processing\offline_map_matching_algorithm.py", line 198, in processAlgorithm
error_code = mm.startViterbiMatchingProcessing(trajectory_layer,
File "C:\Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Offline-MapMatching\mm\map_matcher.py", line 128, in startViterbiMatchingProcessing
check_results = self.hidden_model.setTransitions(fast_map_matching)
File "C:\Users/f/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Offline-MapMatching\mm\hidden_states\hidden_model.py", line 203, in setTransitions
observation_distance = math.sqrt(math.pow(observation.point.asPoint().x() - self.trajectory.observations[i - 1].point.asPoint().x(), 2) + math.pow(observation.point.asPoint().y() - self.trajectory.observations[i - 1].point.asPoint().y(), 2))
ValueError: Null geometry cannot be converted to a point.

Execution failed after 0.67 s

I tried the solutions for the previous issues: reprojection of the network and the trajectory to EPSG:25833, reducing trajectory density to 25 meters (using the plugin function Clip Network), and clipping the network to 250 meters around the trajectory (using the plugin function Reduce Trajectory Density). The problem remains.

I uploaded the original road network file and trajectory file.

I need help to solve this issue, thank you.

[shiyan.zip](https://github.com/jagodki/Offline-MapMatching/files/13448908/shiyan.zip)
[shiyan.zip](https://github.com/jagodki/Offline-MapMatching/files/13448910/shiyan.zip)

**Comment by lzesyr** [comment]
你好，我刚研究这套匹配算法。目前我有个疑问可以请教一下你吗？就是我要怎么生成我所需要的区域的network.geojson文件呢？
