### ISSUE TITLE
AttributeError: 'QgsRasterLayer' object has no attribute 'wkbType'

### ISSUE THREAD

**Issue by anitagraser** [jagodki/Offline-MapMatching#8]
If the project contains a raster layer, the following error pops up. The raster layer has to be removed to use the plugin. 

```
2018-10-02T19:44:52     WARNING    Traceback (most recent call last):
              File "C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Offline-MapMatching\offline_map_matching.py", line 225, in run
              self.populateComboBox('network')
              File "C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Offline-MapMatching\offline_map_matching.py", line 250, in populateComboBox
              self.map_matcher.fillLayerComboBox(self.iface, self.dlg.comboBox_network, 'LINESTRING')
              File "C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Offline-MapMatching\mm\map_matcher.py", line 157, in fillLayerComboBox
              if (QgsWkbTypes.flatType(layer.wkbType()) == QgsWkbTypes.Point and geom_type == 'POINT') or (QgsWkbTypes.flatType(layer.wkbType()) == QgsWkbTypes.LineString and geom_type == 'LINESTRING'):
             AttributeError: 'QgsRasterLayer' object has no attribute 'wkbType'
```

**Comment by jagodki** [comment]
I am sorry about this little mistake. I fixed it and uploaded a new version to the QGIS plugin repository (version 1.1.2).
